package librarymanagement;

//import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nucie
 */
public class HomePage extends javax.swing.JFrame {

    //gets id from 'modifyPanel' and passes to 'modifyRecord' Panel
    private static String prevId;
    
    /**
     * Creates new form HomePage
     * @param username
     */
    public HomePage(String username) {
        initComponents();
        displayTableData();
        
        uNameLabel.setText(username);
        searchField.setText("Find a record");
    }
    private HomePage() {
        
    }
    private final String URL = "jdbc:mysql://localhost:3306/Library_db";
    private final String UNAME = "root";
    private final String UPWD = "";
    
    
    Connection con = null;
    PreparedStatement ps  =null;
    ResultSet rs = null;
    
    private void displayTableData(){
        
        try{  
            con = DriverManager.getConnection(URL, UNAME, UPWD);
            String sql = "SELECT * FROM Library_Books";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            //display book details from database into table using rs2xml.jar
            displayBooksTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        mainBodyPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        menuIconLabel = new javax.swing.JLabel();
        uNameLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        logoutLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        allBooksButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        allBooksPanel = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        displayBooksPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayBooksTable = new javax.swing.JTable();
        deletePanel = new javax.swing.JPanel();
        bookIdLabel2 = new javax.swing.JLabel();
        deleteIdTextField = new javax.swing.JTextField();
        deleteRecordButton1 = new javax.swing.JButton();
        notice = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        modifyRecord = new javax.swing.JPanel();
        bookIdLabel5 = new javax.swing.JLabel();
        bookNameLabel1 = new javax.swing.JLabel();
        bookAuthorLabel1 = new javax.swing.JLabel();
        modifyAuthorTextField = new javax.swing.JTextField();
        modifyIdTextField = new javax.swing.JTextField();
        modifyNameTextField = new javax.swing.JTextField();
        modifyRecordButton = new javax.swing.JButton();
        dateAddedLabel1 = new javax.swing.JLabel();
        modifyDateTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        addBooksPanel = new javax.swing.JPanel();
        bookIdLabel = new javax.swing.JLabel();
        bookNameLabel = new javax.swing.JLabel();
        bookAuthorLabel = new javax.swing.JLabel();
        bookAuthorTextField = new javax.swing.JTextField();
        bookIdTextField = new javax.swing.JTextField();
        bookNameTextField = new javax.swing.JTextField();
        addRecordButton = new javax.swing.JButton();
        dateAddedLabel = new javax.swing.JLabel();
        dateAddedTextField = new javax.swing.JTextField();
        modifyPanel = new javax.swing.JPanel();
        bookIdLabel1 = new javax.swing.JLabel();
        getIdTextField = new javax.swing.JTextField();
        getRecordButton = new javax.swing.JButton();
        header1 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainBodyPanel.setBackground(new java.awt.Color(30, 30, 30));

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));

        uNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        uNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        uNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/images/images (7).jpeg"))); // NOI18N
        uNameLabel.setText("User");

        searchField.setBackground(new java.awt.Color(70, 70, 70));
        searchField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        searchField.setForeground(new java.awt.Color(204, 204, 204));
        searchField.setText("  \n");
        searchField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/images/search.png"))); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));

        logoutLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/images/close.png"))); // NOI18N
        logoutLabel.setText(" Log Out");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        modifyButton.setBackground(new java.awt.Color(255, 255, 255));
        modifyButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        modifyButton.setText("Modify");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(255, 255, 255));
        addButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        allBooksButton.setBackground(new java.awt.Color(255, 255, 255));
        allBooksButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        allBooksButton.setText("All Books");
        allBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBooksButtonActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menuIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(uNameLabel)
                .addGap(41, 41, 41))
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton)
                            .addComponent(modifyButton)
                            .addComponent(allBooksButton)
                            .addComponent(deleteButton))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutLabel)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(uNameLabel)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(allBooksButton)
                .addGap(31, 31, 31)
                .addComponent(addButton)
                .addGap(30, 30, 30)
                .addComponent(modifyButton)
                .addGap(30, 30, 30)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel)
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(258, 258, 258)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(352, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(320, 320, 320)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(290, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(371, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(239, 239, 239)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(452, 452, 452)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(158, Short.MAX_VALUE)))
        );

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        allBooksPanel.setBackground(new java.awt.Color(30, 30, 30));
        allBooksPanel.setPreferredSize(new java.awt.Dimension(600, 553));

        jLayeredPane2.setLayout(new java.awt.CardLayout());

        displayBooksTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        displayBooksTable.setForeground(new java.awt.Color(51, 51, 51));
        displayBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        displayBooksTable.setIntercellSpacing(new java.awt.Dimension(5, 5));
        displayBooksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayBooksTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(displayBooksTable);

        javax.swing.GroupLayout displayBooksPanelLayout = new javax.swing.GroupLayout(displayBooksPanel);
        displayBooksPanel.setLayout(displayBooksPanelLayout);
        displayBooksPanelLayout.setHorizontalGroup(
            displayBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        displayBooksPanelLayout.setVerticalGroup(
            displayBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        jLayeredPane2.add(displayBooksPanel, "card2");

        deletePanel.setBackground(new java.awt.Color(80, 80, 80));

        bookIdLabel2.setBackground(new java.awt.Color(255, 255, 255));
        bookIdLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        bookIdLabel2.setForeground(new java.awt.Color(255, 255, 255));
        bookIdLabel2.setText("Book Id:");

        deleteIdTextField.setBackground(new java.awt.Color(70, 70, 70));
        deleteIdTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        deleteIdTextField.setForeground(new java.awt.Color(204, 204, 204));
        deleteIdTextField.setText("  \n");
        deleteIdTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        deleteIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteIdTextFieldActionPerformed(evt);
            }
        });

        deleteRecordButton1.setBackground(new java.awt.Color(255, 255, 255));
        deleteRecordButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        deleteRecordButton1.setText("Delete Record");
        deleteRecordButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecordButton1ActionPerformed(evt);
            }
        });

        notice.setBackground(new java.awt.Color(255, 255, 255));
        notice.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        notice.setForeground(new java.awt.Color(255, 51, 153));
        notice.setText("Ensure values of record is correct!");

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setText("Enter Id of Book to Delete Book Record");

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(bookIdLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(deleteIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(notice))
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(header)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deletePanelLayout.createSequentialGroup()
                    .addGap(366, 366, 366)
                    .addComponent(deleteRecordButton1)
                    .addContainerGap(116, Short.MAX_VALUE)))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(header)
                .addGap(88, 88, 88)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookIdLabel2)
                    .addComponent(deleteIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(notice)
                .addGap(66, 66, 66))
            .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deletePanelLayout.createSequentialGroup()
                    .addContainerGap(357, Short.MAX_VALUE)
                    .addComponent(deleteRecordButton1)
                    .addGap(61, 61, 61)))
        );

        jLayeredPane2.add(deletePanel, "card4");

        modifyRecord.setBackground(new java.awt.Color(80, 80, 80));

        bookIdLabel5.setBackground(new java.awt.Color(255, 255, 255));
        bookIdLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        bookIdLabel5.setForeground(new java.awt.Color(255, 255, 255));
        bookIdLabel5.setText("Book Id:");

        bookNameLabel1.setBackground(new java.awt.Color(255, 255, 255));
        bookNameLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        bookNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        bookNameLabel1.setText("Book Name:");

        bookAuthorLabel1.setBackground(new java.awt.Color(255, 255, 255));
        bookAuthorLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        bookAuthorLabel1.setForeground(new java.awt.Color(255, 255, 255));
        bookAuthorLabel1.setText("Book Author:");

        modifyAuthorTextField.setBackground(new java.awt.Color(70, 70, 70));
        modifyAuthorTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        modifyAuthorTextField.setForeground(new java.awt.Color(204, 204, 204));
        modifyAuthorTextField.setText("  \n");
        modifyAuthorTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        modifyAuthorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyAuthorTextFieldActionPerformed(evt);
            }
        });

        modifyIdTextField.setBackground(new java.awt.Color(70, 70, 70));
        modifyIdTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        modifyIdTextField.setForeground(new java.awt.Color(204, 204, 204));
        modifyIdTextField.setText("  \n");
        modifyIdTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        modifyIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyIdTextFieldActionPerformed(evt);
            }
        });

        modifyNameTextField.setBackground(new java.awt.Color(70, 70, 70));
        modifyNameTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        modifyNameTextField.setForeground(new java.awt.Color(204, 204, 204));
        modifyNameTextField.setText("  \n");
        modifyNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        modifyNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyNameTextFieldActionPerformed(evt);
            }
        });

        modifyRecordButton.setBackground(new java.awt.Color(255, 255, 255));
        modifyRecordButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        modifyRecordButton.setText("Modify Record");
        modifyRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyRecordButtonActionPerformed(evt);
            }
        });

        dateAddedLabel1.setBackground(new java.awt.Color(255, 255, 255));
        dateAddedLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        dateAddedLabel1.setForeground(new java.awt.Color(255, 255, 255));
        dateAddedLabel1.setText("Date Added:");

        modifyDateTextField.setBackground(new java.awt.Color(70, 70, 70));
        modifyDateTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        modifyDateTextField.setForeground(new java.awt.Color(204, 204, 204));
        modifyDateTextField.setText("  \n");
        modifyDateTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        modifyDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyDateTextFieldActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/images/prev.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modifyRecordLayout = new javax.swing.GroupLayout(modifyRecord);
        modifyRecord.setLayout(modifyRecordLayout);
        modifyRecordLayout.setHorizontalGroup(
            modifyRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyRecordLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(modifyRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(modifyRecordLayout.createSequentialGroup()
                        .addComponent(bookAuthorLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(modifyAuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyRecordLayout.createSequentialGroup()
                        .addComponent(bookIdLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modifyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modifyRecordLayout.createSequentialGroup()
                        .addComponent(bookNameLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(modifyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modifyRecordLayout.createSequentialGroup()
                        .addComponent(dateAddedLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modifyDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyRecordLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifyRecordButton)
                .addGap(100, 100, 100))
        );
        modifyRecordLayout.setVerticalGroup(
            modifyRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyRecordLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(modifyRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modifyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookIdLabel5))
                .addGap(48, 48, 48)
                .addGroup(modifyRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modifyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookNameLabel1))
                .addGap(47, 47, 47)
                .addGroup(modifyRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookAuthorLabel1)
                    .addComponent(modifyAuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(modifyRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateAddedLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modifyDateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(modifyRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(modifyRecordButton))
                .addGap(53, 53, 53))
        );

        jLayeredPane2.add(modifyRecord, "card2");

        addBooksPanel.setBackground(new java.awt.Color(80, 80, 80));

        bookIdLabel.setBackground(new java.awt.Color(255, 255, 255));
        bookIdLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        bookIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookIdLabel.setText("Book Id:");

        bookNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        bookNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        bookNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookNameLabel.setText("Book Name:");

        bookAuthorLabel.setBackground(new java.awt.Color(255, 255, 255));
        bookAuthorLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        bookAuthorLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookAuthorLabel.setText("Book Author:");

        bookAuthorTextField.setBackground(new java.awt.Color(70, 70, 70));
        bookAuthorTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bookAuthorTextField.setForeground(new java.awt.Color(204, 204, 204));
        bookAuthorTextField.setText("  \n");
        bookAuthorTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        bookAuthorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAuthorTextFieldActionPerformed(evt);
            }
        });

        bookIdTextField.setBackground(new java.awt.Color(70, 70, 70));
        bookIdTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bookIdTextField.setForeground(new java.awt.Color(204, 204, 204));
        bookIdTextField.setText("  \n");
        bookIdTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        bookIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIdTextFieldActionPerformed(evt);
            }
        });

        bookNameTextField.setBackground(new java.awt.Color(70, 70, 70));
        bookNameTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bookNameTextField.setForeground(new java.awt.Color(204, 204, 204));
        bookNameTextField.setText("  \n");
        bookNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        bookNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameTextFieldActionPerformed(evt);
            }
        });

        addRecordButton.setBackground(new java.awt.Color(255, 255, 255));
        addRecordButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        addRecordButton.setText("Add Record");
        addRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecordButtonActionPerformed(evt);
            }
        });

        dateAddedLabel.setBackground(new java.awt.Color(255, 255, 255));
        dateAddedLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        dateAddedLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateAddedLabel.setText("Date Added:");

        dateAddedTextField.setBackground(new java.awt.Color(70, 70, 70));
        dateAddedTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        dateAddedTextField.setForeground(new java.awt.Color(204, 204, 204));
        dateAddedTextField.setText("  \n");
        dateAddedTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        dateAddedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateAddedTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addBooksPanelLayout = new javax.swing.GroupLayout(addBooksPanel);
        addBooksPanel.setLayout(addBooksPanelLayout);
        addBooksPanelLayout.setHorizontalGroup(
            addBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBooksPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(addBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addRecordButton)
                    .addGroup(addBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(addBooksPanelLayout.createSequentialGroup()
                            .addComponent(bookAuthorLabel)
                            .addGap(26, 26, 26)
                            .addComponent(bookAuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addBooksPanelLayout.createSequentialGroup()
                            .addComponent(bookIdLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addBooksPanelLayout.createSequentialGroup()
                            .addComponent(bookNameLabel)
                            .addGap(35, 35, 35)
                            .addComponent(bookNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addBooksPanelLayout.createSequentialGroup()
                            .addComponent(dateAddedLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateAddedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        addBooksPanelLayout.setVerticalGroup(
            addBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBooksPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(addBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookIdLabel))
                .addGap(48, 48, 48)
                .addGroup(addBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookNameLabel))
                .addGap(47, 47, 47)
                .addGroup(addBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookAuthorLabel)
                    .addComponent(bookAuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(addBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateAddedLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateAddedTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(addRecordButton)
                .addGap(78, 78, 78))
        );

        jLayeredPane2.add(addBooksPanel, "card3");

        modifyPanel.setBackground(new java.awt.Color(80, 80, 80));

        bookIdLabel1.setBackground(new java.awt.Color(255, 255, 255));
        bookIdLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        bookIdLabel1.setForeground(new java.awt.Color(255, 255, 255));
        bookIdLabel1.setText("Book Id:");

        getIdTextField.setBackground(new java.awt.Color(70, 70, 70));
        getIdTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        getIdTextField.setForeground(new java.awt.Color(204, 204, 204));
        getIdTextField.setText("  \n");
        getIdTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        getIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getIdTextFieldActionPerformed(evt);
            }
        });

        getRecordButton.setBackground(new java.awt.Color(255, 255, 255));
        getRecordButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getRecordButton.setText("Get Record");
        getRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRecordButtonActionPerformed(evt);
            }
        });

        header1.setBackground(new java.awt.Color(255, 255, 255));
        header1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        header1.setForeground(new java.awt.Color(255, 255, 255));
        header1.setText("Enter Id of Book to Fetch Book Record to Modify");

        javax.swing.GroupLayout modifyPanelLayout = new javax.swing.GroupLayout(modifyPanel);
        modifyPanel.setLayout(modifyPanelLayout);
        modifyPanelLayout.setHorizontalGroup(
            modifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(modifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getRecordButton)
                    .addGroup(modifyPanelLayout.createSequentialGroup()
                        .addComponent(header1)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modifyPanelLayout.createSequentialGroup()
                        .addComponent(bookIdLabel1)
                        .addGap(81, 81, 81)
                        .addComponent(getIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        modifyPanelLayout.setVerticalGroup(
            modifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(header1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(modifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookIdLabel1)
                    .addComponent(getIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(getRecordButton)
                .addGap(126, 126, 126))
        );

        jLayeredPane2.add(modifyPanel, "card5");

        javax.swing.GroupLayout allBooksPanelLayout = new javax.swing.GroupLayout(allBooksPanel);
        allBooksPanel.setLayout(allBooksPanelLayout);
        allBooksPanelLayout.setHorizontalGroup(
            allBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allBooksPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        allBooksPanelLayout.setVerticalGroup(
            allBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allBooksPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLayeredPane1.add(allBooksPanel, "card4");

        javax.swing.GroupLayout mainBodyPanelLayout = new javax.swing.GroupLayout(mainBodyPanel);
        mainBodyPanel.setLayout(mainBodyPanelLayout);
        mainBodyPanelLayout.setHorizontalGroup(
            mainBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBodyPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainBodyPanelLayout.setVerticalGroup(
            mainBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainBodyPanelLayout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1119, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        //log out and display login Page
        LoginPage login = new LoginPage();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        
         //search record from table
         String search = searchField.getText();
         
         if(search.isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Field Empty");
         }else{
             try{  
                con = DriverManager.getConnection(URL, UNAME, UPWD);
                String sql = "SELECT * FROM Library_Books WHERE bookid = ? || bookname = ? || bookauthor = ? || dateadded = ?";

                ps = con.prepareStatement(sql);
                ps.setString(1, search);
                ps.setString(2, search);
                ps.setString(3, search);
                ps.setString(4, search);

                rs = ps.executeQuery();
                
                displayBooksTable.setModel(DbUtils.resultSetToTableModel(rs));
                 
                
             }catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, ex);
            }
         }
         
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // display delete button panel
        displayBooksPanel.setVisible(false);
        addBooksPanel.setVisible(false);
        modifyPanel.setVisible(false);
        deletePanel.setVisible(true);
        modifyRecord.setVisible(false);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        //display modifyPanel
        displayBooksPanel.setVisible(false);
        addBooksPanel.setVisible(false);
        deletePanel.setVisible(false);
        modifyPanel.setVisible(true);
        modifyRecord.setVisible(false);
       
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // display addBooks panel
        modifyPanel.setVisible(false);
        modifyRecord.setVisible(false);
        deletePanel.setVisible(false);
        displayBooksPanel.setVisible(false);
        addBooksPanel.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void allBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBooksButtonActionPerformed
        // Display all books home i.e displayBooksPanel
        displayTableData();
        modifyPanel.setVisible(false);
        modifyRecord.setVisible(false);
        deletePanel.setVisible(false);
        addBooksPanel.setVisible(false);
        displayBooksPanel.setVisible(true);
        
    }//GEN-LAST:event_allBooksButtonActionPerformed

    private void displayBooksTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayBooksTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_displayBooksTableMouseClicked

    private void bookAuthorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAuthorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookAuthorTextFieldActionPerformed

    private void bookIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIdTextFieldActionPerformed

    private void bookNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNameTextFieldActionPerformed

    private void addRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecordButtonActionPerformed
        // from addBooksPanel get values from textField and insert into database
        String bookId = bookIdTextField.getText().trim();
        String bookName = bookNameTextField.getText().trim();
        String bookAuthor = bookAuthorTextField.getText().trim();
        String dateAdded = dateAddedTextField.getText().trim();
        
        if(bookId.isEmpty() || bookName.isEmpty() || bookAuthor.isEmpty() || dateAdded.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Field Empty");
        }else{
            
                try {
                con = DriverManager.getConnection(URL, UNAME, UPWD);
                String sql = "INSERT INTO Library_Books VALUES( ?, ?, ?, ?)";
                ps = con.prepareStatement(sql);

                ps.setString(1, bookId);
                ps.setString(2, bookName);
                ps.setString(3, bookAuthor);
                ps.setString(4, dateAdded);

                if(ps.executeUpdate() > 0){
                    //successful
                    JOptionPane.showMessageDialog(rootPane, "Data Saved");
                    bookIdTextField.setText("");
                    bookNameTextField.setText("");
                    bookAuthorTextField.setText("");
                    dateAddedTextField.setText("");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }

        }
        
    }//GEN-LAST:event_addRecordButtonActionPerformed

    private void dateAddedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateAddedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateAddedTextFieldActionPerformed

    private void deleteIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteIdTextFieldActionPerformed

    private void deleteRecordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRecordButton1ActionPerformed
        // from deleteBooksPanel get values from textField and compare with database to delete record
        String bookId = deleteIdTextField.getText().trim();
        
        if(bookId.isEmpty()){  
            JOptionPane.showMessageDialog(rootPane, "Field Empty");
        }else{
            try {
                con = DriverManager.getConnection(URL, UNAME, UPWD);
                String delQuery = "";
                String sql = "SELECT * FROM Library_Books WHERE BookId = ?";
                ps = con.prepareStatement(sql);
                
                ps.setString(1, bookId);

                rs = ps.executeQuery();
                if(rs.next()){
                    //successful , delete record
                    delQuery = "DELETE FROM Library_Books WHERE BookId = ?";
                    ps = con.prepareStatement(delQuery);
                    ps.setString(1, bookId);
                    
                    if(ps.executeUpdate() > 0){
                        JOptionPane.showMessageDialog(rootPane, "Record Deleted Successfully");
                    }
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }

        }
        
    }//GEN-LAST:event_deleteRecordButton1ActionPerformed

    private void getIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getIdTextFieldActionPerformed

    private void getRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRecordButtonActionPerformed
        // get id and display on modifyRecord panel
        String id = getIdTextField.getText().trim();
        
        //check if id exists and pass to modifyRecord Panel
        if(id.isEmpty()){  
            JOptionPane.showMessageDialog(rootPane, "Field Empty");
        }else{
            try {
                con = DriverManager.getConnection(URL, UNAME, UPWD);
                
                String sql = "SELECT * FROM Library_Books WHERE BookId = ?";
                ps = con.prepareStatement(sql);
                
                ps.setString(1, id);

                rs = ps.executeQuery();
                
                if(rs.next()){
                    //if record exists display modifyrecord Panel
                    
                    modifyIdTextField.setText(rs.getString("bookid"));
                    modifyNameTextField.setText(rs.getString("bookname"));
                    modifyAuthorTextField.setText(rs.getString("bookauthor"));
                    modifyDateTextField.setText(rs.getString("dateadded"));
                    prevId = id;
                    
                    modifyPanel.setVisible(false);
                    modifyRecord.setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Invalid Book Id");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }

        }
        
    }//GEN-LAST:event_getRecordButtonActionPerformed

    private void modifyAuthorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyAuthorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyAuthorTextFieldActionPerformed

    private void modifyIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyIdTextFieldActionPerformed

    private void modifyNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyNameTextFieldActionPerformed

    private void modifyRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyRecordButtonActionPerformed
        // modify new records from modify record panel
        
        String bookId = modifyIdTextField.getText().trim();
        String bookName = modifyNameTextField.getText().trim();
        String bookAuthor = modifyAuthorTextField.getText().trim();
        String newDate = modifyDateTextField.getText().trim();
        
        if(bookId.isEmpty() || bookName.isEmpty() || bookAuthor.isEmpty() || newDate.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Field Empty");
        }else{
            
                try {
                con = DriverManager.getConnection(URL, UNAME, UPWD);
                String sql = "UPDATE Library_books SET bookid = ?, bookname = ?, bookauthor = ?, dateadded = ? WHERE bookid = ?";
                ps = con.prepareStatement(sql);

                ps.setString(1, bookId);
                ps.setString(2, bookName);
                ps.setString(3, bookAuthor);
                ps.setString(4, newDate);
                ps.setString(5, prevId);

                if(ps.executeUpdate() > 0){
                    //successful
                    JOptionPane.showMessageDialog(rootPane, "Data Saved");
                    modifyIdTextField.setText("");
                    modifyNameTextField.setText("");
                    modifyAuthorTextField.setText("");
                    modifyDateTextField.setText("");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }

        }
        
        
    }//GEN-LAST:event_modifyRecordButtonActionPerformed

    private void modifyDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyDateTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        //go back to modifyPanel
        modifyRecord.setVisible(false);
        modifyPanel.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ModifyNameTextField1;
    private javax.swing.JTextField ModifyNameTextField2;
    private javax.swing.JPanel addBooksPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addRecordButton;
    private javax.swing.JButton allBooksButton;
    private javax.swing.JPanel allBooksPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bookAuthorLabel;
    private javax.swing.JLabel bookAuthorLabel1;
    private javax.swing.JLabel bookAuthorLabel2;
    private javax.swing.JLabel bookAuthorLabel3;
    private javax.swing.JTextField bookAuthorTextField;
    private javax.swing.JLabel bookIdLabel;
    private javax.swing.JLabel bookIdLabel1;
    private javax.swing.JLabel bookIdLabel2;
    private javax.swing.JLabel bookIdLabel3;
    private javax.swing.JLabel bookIdLabel4;
    private javax.swing.JLabel bookIdLabel5;
    private javax.swing.JTextField bookIdTextField;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JLabel bookNameLabel1;
    private javax.swing.JLabel bookNameLabel2;
    private javax.swing.JLabel bookNameLabel3;
    private javax.swing.JTextField bookNameTextField;
    private javax.swing.JLabel dateAddedLabel;
    private javax.swing.JLabel dateAddedLabel1;
    private javax.swing.JLabel dateAddedLabel2;
    private javax.swing.JLabel dateAddedLabel3;
    private javax.swing.JTextField dateAddedTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField deleteIdTextField;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton deleteRecordButton1;
    private javax.swing.JPanel displayBooksPanel;
    private javax.swing.JTable displayBooksTable;
    private javax.swing.JTextField getIdTextField;
    private javax.swing.JButton getRecordButton;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel mainBodyPanel;
    private javax.swing.JLabel menuIconLabel;
    private javax.swing.JTextField modifyAuthorTextField;
    private javax.swing.JTextField modifyAuthorTextField1;
    private javax.swing.JTextField modifyAuthorTextField2;
    private javax.swing.JButton modifyButton;
    private javax.swing.JTextField modifyDateTextField;
    private javax.swing.JTextField modifyDateTextField1;
    private javax.swing.JTextField modifyDateTextField2;
    private javax.swing.JTextField modifyIdTextField;
    private javax.swing.JTextField modifyIdTextField1;
    private javax.swing.JTextField modifyIdTextField2;
    private javax.swing.JTextField modifyNameTextField;
    private javax.swing.JPanel modifyPanel;
    private javax.swing.JPanel modifyPanel1;
    private javax.swing.JPanel modifyPanel2;
    private javax.swing.JPanel modifyRecord;
    private javax.swing.JButton modifyRecordButton;
    private javax.swing.JButton modifyRecordButton1;
    private javax.swing.JButton modifyRecordButton2;
    private javax.swing.JLabel notice;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel uNameLabel;
    // End of variables declaration//GEN-END:variables
}
